SportsECommerce/Models/ErrorViewModel.cs
namespace SportsECommerce.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

SportsECommerce/Models/Product.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
namespace SportsECommerce.Models
{
    public class Product
    {
        [Key]
        public long? Id { get; set; }
        public string Name { get; set; } = String.Empty;
        public string Description { get; set; } = String.Empty;
        [Column(TypeName = "decimal(8, 2)")] // Column attribute to specify the SQL Data Type
        public decimal Price { get; set; }
        public string Category { get; set; } = String.Empty;
    }
}

SportsECommerce/Models/Repository/EFStoreRepository.cs
using SportsECommerce.Data;

namespace SportsECommerce.Models.Repository
{
    public class EFStoreRepository : IStoreRepository
    {
        private StoreDbContext context;

        public EFStoreRepository(StoreDbContext ctx)
        {
            context = ctx;
        }

        public IQueryable<Product> Products => context.Products;
    }
}

SportsECommerce/Models/Repository/IStoreRepository.cs
namespace SportsECommerce.Models.Repository
{
    public interface IStoreRepository
    {
        // IQueryable allows a collection of objects to be queried efficiently
        IQueryable<Product> Products { get; }
    }
}

SportsECommerce/Models/SeedData/SeedData.cs
using SportsECommerce.Data;
using Microsoft.EntityFrameworkCore;
namespace SportsECommerce.Models.SeedData
{
    public static class SeedData
    {
        //
        public static void EnsurePopulated(IApplicationBuilder app)
        {
            StoreDbContext context = app.ApplicationServices.CreateScope().ServiceProvider.GetRequiredService<StoreDbContext>();

            if (context.Database.GetPendingMigrations().Any())
            {
                context.Database.Migrate();
            }

            if (!context.Products.Any())
            {
                context.Products.AddRange(
                    new Product
                    {
                        Name = "Kayak",
                        Description = "A boat for one person",
                        Category = "Water Sports",
                        Price = 275
                    },
                    new Product
                    {
                        Name = "Soccer Ball",
                        Description = "FIFA-approved Ball",
                        Category = "Soccer",
                        Price = 19.50m
                    },
                    new Product
                    {
                        Name = "Stadium",
                        Description = "35,000-seat stadium",
                        Category = "Soccer",
                        Price = 79500
                    },
                    new Product
                    {
                        Name = "Baseball Ball",
                        Description = "MLB Approved Ball",
                        Category = "Baseball",
                        Price = 299.99m
                    });


                context.SaveChanges();

            }

        }
    }
}

SportsECommerce/Models/ViewModel/PagingInfo.cs
namespace SportsECommerce.Models.ViewModel
{
    public class PagingInfo
    {
        // Tag helper: pass the information to the view about the number of pages available, current pages, and total number of products
        public int TotalItems { get; set; }
        public int ItemsPerPage { get; set; }
        public int CurrentPage { get; set; }

        public int TotalPages => (int)Math.Ceiling((decimal)TotalItems / ItemsPerPage);
    }
}

SportsECommerce/Models/ViewModel/ProductsListViewModel.cs
namespace SportsECommerce.Models.ViewModel
{
    public class ProductsListViewModel
    {
        public IEnumerable<Product> Products { get; set; } = Enumerable.Empty<Product>();
        public PagingInfo PagingInfo { get; set; } = new();
        public string? CurrentCategory { get; set; }
    }
}

SportsECommerce/Components/NavigationMenuViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Razor.Compilation;
using NuGet.Protocol.Core.Types;
using SportsECommerce.Models.Repository;

namespace SportsECommerce.Components
{
    public class NavigationMenuViewComponent : ViewComponent
    {
        private IStoreRepository _repository;

        public NavigationMenuViewComponent(IStoreRepository repo)
        {
            _repository = repo;
        }

        public IViewComponentResult Invoke()
        {
            ViewBag.SelectedCategory = RouteData?.Values["category"];
            return View(_repository.Products
            .Select(x => x.Category)
            .Distinct()
            .OrderBy(x => x));
        }

    }
}

SportsECommerce/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using SportsECommerce.Models.Repository;
using SportsECommerce.Models.ViewModel;
using System.Diagnostics;

namespace SportsECommerce.Controllers
{
    public class HomeController : Controller
    {
        private IStoreRepository repository;
        // specifies four products per page
        public int PageSize = 4;

        public HomeController(IStoreRepository repo)
        {
            repository = repo;
        }

        public IActionResult Index(string? category, int productPage = 1)
        {
            return View(new ProductsListViewModel
            {
                Products = repository.Products.
                Where(p => category == null || p.Category == category).
                OrderBy(p => p.Id).
                Skip((productPage - 1) * PageSize).
                Take(PageSize),
                PagingInfo = new PagingInfo
                {
                    CurrentPage = productPage,
                    ItemsPerPage = PageSize,
                    TotalItems = category == null ? repository.Products.Count() : repository.Products
                    .Where(e => e.Category == category).Count()
                },
                CurrentCategory = category
            });
        }
    }
}

SportsECommerce/Views/Home/Components/NavigationMenu/Default.cshtml
@model IEnumerable<string>
<div class="d-grid gap-2">
    <a class="btn btn-outline-secondary" asp-action="Index"
       asp-controller="Home" asp-route-category="">
        Home
    </a>
    @foreach (string category in Model ?? Enumerable.Empty<string>())
    {
        <a class="btn @(category == ViewBag.SelectedCategory ? "btn-primary": "btn-outline-secondary")"
           asp-action="Index" asp-controller="Home"
           asp-route-category="@category"
           asp-route-productPage="1">
            @category
        </a>
    }
</div>

SportsECommerce/Views/Home/Index.cshtml
@model ProductsListViewModel

@{
    ViewData["Title"] = "Home Page";
}



<!--Displaying of views in the sample seed data-->
@foreach (var p in Model.Products ?? Enumerable.Empty<Product>())
{
    <partial name="ProductSummary" model="p" />
}

<div page-model="@Model?.PagingInfo" page-action="Index" page-classes-enabled="true"
 page-class="btn" page-class-normal="btn-outline-dark"
 page-class-selected="btn-primary" page-url-category="@Model?.CurrentCategory!"
 page-class-selected="btn-primary" class="btn-group pull-right m-1">
</div>
    

SportsECommerce/Views/Shared/ProductSummary.cshtml
@model Product

<!--Partial view to reduce duplication-->
<div class="card card-outline-primary m-1 p-1">
    <div class="bg-faded p-1">
        <h4>
            @Model?.Name
            <span class="badge rounded-pill bg-primary text-white"
                  style="float:right">
                <small>@Model?.Price.ToString("c")</small>
            </span>
        </h4>
    </div>
    <div class="card-text p-1">@Model?.Description</div>
</div>

SportsECommerce/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SportsECommerce</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/SportsECommerce.styles.css" asp-append-version="true" />
</head>
<body>
    <div class="container">
        <div class="bg-dark text-white p-2">
            <span class="navbar-brand ml-2">SPORTS STORE</span>
        </div>
        <div class="row m-1 p-1">
            <div id="categories" class="col-3">
                <vc:navigation-menu />
            </div>
            <div class="col-9">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - SportsECommerce - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>